// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.control.cell;

/**
 * {@link ImageGridCell}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.0.6.jar
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class ImageGridCellBuilder<Z extends ImageGridCell, B extends ImageGridCellBuilder<Z, B>>
        extends org.controlsfx.control.GridCellBuilder<javafx.scene.image.Image, Z, B>
{
    private boolean applied;
    public void applyTo(ImageGridCell instance)
    {
        super.applyTo(instance);
        if (this.applied)
            throw new IllegalStateException();
        //
        this.applied = true;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ImageGridCell build()
    {
        ImageGridCell instance = new ImageGridCell();
        this.applyTo(instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
