// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.transform;

/**
 * {@link Affine}建構器延伸（供客製化）
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link Affine})
 * @param <B> 建構器本身的型態(需繼承{@link AffineMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface AffineMakerExt<Z extends Affine, B extends AffineMaker<Z, B>>
        extends javafx.scene.transform.TransformMakerExt<Z, B>
{
    // nothing yet
}
