// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene;

/**
 * {@link Group}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class GroupBuilder<Z extends Group, B extends GroupBuilder<Z, B>>
        extends javafx.scene.ParentBuilder<Z, B>
{
    private boolean applied;

    protected boolean hasAutoSizeChildren;
    protected boolean valAutoSizeChildren;

    protected boolean hasChildren;
    protected java.util.Collection<javafx.scene.Node> valChildren;

    protected boolean boundAutoSizeChildren;
    protected javafx.beans.value.ObservableValue<? extends Boolean> obsrvAutoSizeChildren;
    public void applyTo(Group instance)
    {
        super.applyTo(instance);
        if (this.applied)
            throw new IllegalStateException();
        if (this.hasAutoSizeChildren)
            instance.setAutoSizeChildren(this.valAutoSizeChildren);
        if (this.hasChildren)
            instance.getChildren().setAll(this.valChildren);
        if (this.boundAutoSizeChildren)
            instance.autoSizeChildrenProperty().bind(this.obsrvAutoSizeChildren);
        //
        this.applied = true;
    }

    @SuppressWarnings("unchecked")
    public B autoSizeChildren(boolean value)
    {
        this.hasAutoSizeChildren = true;
        this.valAutoSizeChildren = value;
        return (B) this;
    }

    @SuppressWarnings("unchecked")
    public B children(java.util.Collection<javafx.scene.Node> value)
    {
        this.hasChildren = true;
        this.valChildren = value;
        return (B) this;
    }

    @SafeVarargs
    @SuppressWarnings("unchecked")
    public final B children(javafx.scene.Node... value)
    {
        this.hasChildren = true;
        this.valChildren = java.util.Arrays.asList(value);
        return (B) this;
    }

    @SuppressWarnings("unchecked")
    public B bindAutoSizeChildren(javafx.beans.value.ObservableValue<? extends Boolean> source)
    {
        assert (source != null);
        this.boundAutoSizeChildren = true;
        this.obsrvAutoSizeChildren = source;
        return (B) this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Group build()
    {
        Group instance = new Group();
        this.applyTo(instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
