// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.tools;

/**
 * {@link Utils}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.0.6.jar
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class UtilsBuilder<Z extends Utils, B extends UtilsBuilder<Z, B>>
        extends jxtn.jfx.builders.AbstractBuilder<Z, B>
{
    private boolean applied;
    public void applyTo(Utils instance)
    {
        super.applyTo(instance);
        if (this.applied)
            throw new IllegalStateException();
        //
        this.applied = true;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Utils build()
    {
        Utils instance = new Utils();
        this.applyTo(instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
