// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.stage;

/**
 * {@link FileChooser.ExtensionFilter}建構器。
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link FileChooser.ExtensionFilter})
 * @param <B> 建構器本身的型態(需繼承{@link FileChooser.ExtensionFilterMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class FileChooser_ExtensionFilterMaker<Z extends FileChooser.ExtensionFilter, B extends FileChooser_ExtensionFilterMaker<Z, B>>
        extends jxtn.jfx.makers.AbstractMaker<Z, B>
        implements FileChooser_ExtensionFilterMakerExt<Z, B>
{

    @Override
    public void applyTo(Z instance)
    {
        super.applyTo(instance);
    }

    /**
     * 建構{@link FileChooser.ExtensionFilter}物件。
     *
     * @return 新的{@link FileChooser.ExtensionFilter}物件實體
     */
    @SuppressWarnings("unchecked")
    public FileChooser.ExtensionFilter build(java.lang.String arg0, java.lang.String[] arg1)
    {
        FileChooser.ExtensionFilter instance = new FileChooser.ExtensionFilter(arg0, arg1);
        this.applyTo((Z) instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }

    /**
     * 建構{@link FileChooser.ExtensionFilter}物件。
     *
     * @return 新的{@link FileChooser.ExtensionFilter}物件實體
     */
    @SuppressWarnings("unchecked")
    public FileChooser.ExtensionFilter build(java.lang.String arg0, java.util.List<java.lang.String> arg1)
    {
        FileChooser.ExtensionFilter instance = new FileChooser.ExtensionFilter(arg0, arg1);
        this.applyTo((Z) instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
