// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.media;

/**
 * {@link AudioTrack}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link AudioTrack})
 * @param <B> 建構器本身的型態(需繼承{@link AudioTrackBuilder})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class AudioTrackBuilder<Z extends AudioTrack, B extends AudioTrackBuilder<Z, B>>
        extends javafx.scene.media.TrackBuilder<Z, B>
        implements AudioTrackBuilderExt<Z, B>
{

    @Override
    public void applyTo(Z instance)
    {
        super.applyTo(instance);
    }
}
