// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.layout;

/**
 * {@link HBox}建構器延伸（供客製化）
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link HBox})
 * @param <B> 建構器本身的型態(需繼承{@link HBoxMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface HBoxMakerExt<Z extends HBox, B extends HBoxMaker<Z, B>>
        extends javafx.scene.layout.PaneMakerExt<Z, B>
{
    // nothing yet
}
