// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.control;

/**
 * {@link InfoOverlay}建構器延伸（供客製化）
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.0.6_20.jar
 * @param <Z> 要建構的物件型態(需繼承{@link InfoOverlay})
 * @param <B> 建構器本身的型態(需繼承{@link InfoOverlayBuilder})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface InfoOverlayBuilderExt<Z extends InfoOverlay, B extends InfoOverlayBuilder<Z, B>>
        extends javafx.scene.control.ControlBuilderExt<Z, B>
{
    // nothing yet
}
