// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.control;

/**
 * {@link PlusMinusSlider}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.0.6.jar
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class PlusMinusSliderBuilder<Z extends PlusMinusSlider, B extends PlusMinusSliderBuilder<Z, B>>
        extends javafx.scene.control.ControlBuilder<Z, B>
{
    private boolean applied;

    protected boolean hasOnValueChanged;
    protected javafx.event.EventHandler<org.controlsfx.control.PlusMinusSlider.PlusMinusEvent> valOnValueChanged;

    protected boolean hasOrientation;
    protected javafx.geometry.Orientation valOrientation;

    protected boolean boundOnValueChanged;
    protected javafx.beans.value.ObservableValue<? extends javafx.event.EventHandler<org.controlsfx.control.PlusMinusSlider.PlusMinusEvent>> obsrvOnValueChanged;

    protected boolean boundOrientation;
    protected javafx.beans.value.ObservableValue<? extends javafx.geometry.Orientation> obsrvOrientation;
    public void applyTo(PlusMinusSlider instance)
    {
        super.applyTo(instance);
        if (this.applied)
            throw new IllegalStateException();
        if (this.hasOnValueChanged)
            instance.setOnValueChanged(this.valOnValueChanged);
        if (this.hasOrientation)
            instance.setOrientation(this.valOrientation);
        if (this.boundOnValueChanged)
            instance.onValueChangedProperty().bind(this.obsrvOnValueChanged);
        if (this.boundOrientation)
            instance.orientationProperty().bind(this.obsrvOrientation);
        //
        this.applied = true;
    }

    @SuppressWarnings("unchecked")
    public B onValueChanged(javafx.event.EventHandler<org.controlsfx.control.PlusMinusSlider.PlusMinusEvent> value)
    {
        this.hasOnValueChanged = true;
        this.valOnValueChanged = value;
        return (B) this;
    }

    @SuppressWarnings("unchecked")
    public B orientation(javafx.geometry.Orientation value)
    {
        this.hasOrientation = true;
        this.valOrientation = value;
        return (B) this;
    }

    @SuppressWarnings("unchecked")
    public B bindOnValueChanged(javafx.beans.value.ObservableValue<? extends javafx.event.EventHandler<org.controlsfx.control.PlusMinusSlider.PlusMinusEvent>> source)
    {
        assert (source != null);
        this.boundOnValueChanged = true;
        this.obsrvOnValueChanged = source;
        return (B) this;
    }

    @SuppressWarnings("unchecked")
    public B bindOrientation(javafx.beans.value.ObservableValue<? extends javafx.geometry.Orientation> source)
    {
        assert (source != null);
        this.boundOrientation = true;
        this.obsrvOrientation = source;
        return (B) this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PlusMinusSlider build()
    {
        PlusMinusSlider instance = new PlusMinusSlider();
        this.applyTo(instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
