// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.control;

/**
 * {@link PopOver}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.0.6_20.jar
 * @param <Z> 要建構的物件型態(需繼承{@link PopOver})
 * @param <B> 建構器本身的型態(需繼承{@link PopOverBuilder})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class PopOverBuilder<Z extends PopOver, B extends PopOverBuilder<Z, B>>
        extends javafx.scene.control.PopupControlBuilder<Z, B>
{

    private boolean hasArrowIndent;
    private double valArrowIndent;

    private boolean hasArrowLocation;
    private org.controlsfx.control.PopOver.ArrowLocation valArrowLocation;

    private boolean hasArrowSize;
    private double valArrowSize;

    private boolean hasContentNode;
    private javafx.scene.Node valContentNode;

    private boolean hasCornerRadius;
    private double valCornerRadius;

    private boolean hasDetachable;
    private boolean valDetachable;

    private boolean hasDetached;
    private boolean valDetached;

    private boolean hasDetachedTitle;
    private java.lang.String valDetachedTitle;

    private boolean boundArrowIndent;
    private javafx.beans.value.ObservableValue<? extends Double> obsrvArrowIndent;

    private boolean boundArrowLocation;
    private javafx.beans.value.ObservableValue<? extends org.controlsfx.control.PopOver.ArrowLocation> obsrvArrowLocation;

    private boolean boundArrowSize;
    private javafx.beans.value.ObservableValue<? extends Double> obsrvArrowSize;

    private boolean boundContentNode;
    private javafx.beans.value.ObservableValue<? extends javafx.scene.Node> obsrvContentNode;

    private boolean boundCornerRadius;
    private javafx.beans.value.ObservableValue<? extends Double> obsrvCornerRadius;

    private boolean boundDetachable;
    private javafx.beans.value.ObservableValue<? extends Boolean> obsrvDetachable;

    private boolean boundDetached;
    private javafx.beans.value.ObservableValue<? extends Boolean> obsrvDetached;

    private boolean boundDetachedTitle;
    private javafx.beans.value.ObservableValue<? extends String> obsrvDetachedTitle;

    @Override
    public void applyTo(Z instance)
    {
        super.applyTo(instance);
        if (this.hasArrowIndent)
            instance.setArrowIndent(this.valArrowIndent);
        if (this.hasArrowLocation)
            instance.setArrowLocation(this.valArrowLocation);
        if (this.hasArrowSize)
            instance.setArrowSize(this.valArrowSize);
        if (this.hasContentNode)
            instance.setContentNode(this.valContentNode);
        if (this.hasCornerRadius)
            instance.setCornerRadius(this.valCornerRadius);
        if (this.hasDetachable)
            instance.setDetachable(this.valDetachable);
        if (this.hasDetached)
            instance.setDetached(this.valDetached);
        if (this.hasDetachedTitle)
            instance.setDetachedTitle(this.valDetachedTitle);
        if (this.boundArrowIndent)
            instance.arrowIndentProperty().bind(this.obsrvArrowIndent);
        if (this.boundArrowLocation)
            instance.arrowLocationProperty().bind(this.obsrvArrowLocation);
        if (this.boundArrowSize)
            instance.arrowSizeProperty().bind(this.obsrvArrowSize);
        if (this.boundContentNode)
            instance.contentNodeProperty().bind(this.obsrvContentNode);
        if (this.boundCornerRadius)
            instance.cornerRadiusProperty().bind(this.obsrvCornerRadius);
        if (this.boundDetachable)
            instance.detachableProperty().bind(this.obsrvDetachable);
        if (this.boundDetached)
            instance.detachedProperty().bind(this.obsrvDetached);
        if (this.boundDetachedTitle)
            instance.detachedTitleProperty().bind(this.obsrvDetachedTitle);
    }

    /**
     * 設定屬性{@link PopOver#setArrowIndent(double)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B arrowIndent(double value)
    {
        this.hasArrowIndent = true;
        this.valArrowIndent = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#setArrowLocation(org.controlsfx.control.PopOver.ArrowLocation)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B arrowLocation(org.controlsfx.control.PopOver.ArrowLocation value)
    {
        this.hasArrowLocation = true;
        this.valArrowLocation = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#setArrowSize(double)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B arrowSize(double value)
    {
        this.hasArrowSize = true;
        this.valArrowSize = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#setContentNode(javafx.scene.Node)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B contentNode(javafx.scene.Node value)
    {
        this.hasContentNode = true;
        this.valContentNode = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#setCornerRadius(double)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B cornerRadius(double value)
    {
        this.hasCornerRadius = true;
        this.valCornerRadius = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#setDetachable(boolean)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B detachable(boolean value)
    {
        this.hasDetachable = true;
        this.valDetachable = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#setDetached(boolean)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B detached(boolean value)
    {
        this.hasDetached = true;
        this.valDetached = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#setDetachedTitle(java.lang.String)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B detachedTitle(java.lang.String value)
    {
        this.hasDetachedTitle = true;
        this.valDetachedTitle = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#arrowIndentProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindArrowIndent(javafx.beans.value.ObservableValue<? extends Double> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundArrowIndent = true;
        this.obsrvArrowIndent = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#arrowLocationProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindArrowLocation(javafx.beans.value.ObservableValue<? extends org.controlsfx.control.PopOver.ArrowLocation> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundArrowLocation = true;
        this.obsrvArrowLocation = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#arrowSizeProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindArrowSize(javafx.beans.value.ObservableValue<? extends Double> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundArrowSize = true;
        this.obsrvArrowSize = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#contentNodeProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindContentNode(javafx.beans.value.ObservableValue<? extends javafx.scene.Node> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundContentNode = true;
        this.obsrvContentNode = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#cornerRadiusProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindCornerRadius(javafx.beans.value.ObservableValue<? extends Double> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundCornerRadius = true;
        this.obsrvCornerRadius = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#detachableProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindDetachable(javafx.beans.value.ObservableValue<? extends Boolean> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundDetachable = true;
        this.obsrvDetachable = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#detachedProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindDetached(javafx.beans.value.ObservableValue<? extends Boolean> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundDetached = true;
        this.obsrvDetached = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link PopOver#detachedTitleProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindDetachedTitle(javafx.beans.value.ObservableValue<? extends String> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundDetachedTitle = true;
        this.obsrvDetachedTitle = source;
        return (B) this;
    }

    /**
     * 建構{@link PopOver}物件
     *
     * @return 新的{@link PopOver}物件實體
     */
    @Override
    @SuppressWarnings("unchecked")
    public PopOver build()
    {
        PopOver instance = new PopOver();
        this.applyTo((Z) instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
