// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.control;

/**
 * {@link Cell}建構器延伸（供客製化）
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link Cell})
 * @param <B> 建構器本身的型態(需繼承{@link CellMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface CellMakerExt<T extends java.lang.Object, Z extends Cell<T>, B extends CellMaker<T, Z, B>>
        extends javafx.scene.control.LabeledMakerExt<Z, B>
{
    // nothing yet
}
