// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.control;

/**
 * {@link ComboBoxBase}建構器延伸（供客製化）
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link ComboBoxBase})
 * @param <B> 建構器本身的型態(需繼承{@link ComboBoxBaseBuilder})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface ComboBoxBaseBuilderExt<T extends java.lang.Object, Z extends ComboBoxBase<T>, B extends ComboBoxBaseBuilder<T, Z, B>>
        extends javafx.scene.control.ControlBuilderExt<Z, B>
{
    // nothing yet
}
