// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.control;

/**
 * {@link DatePicker}建構器延伸（供客製化）
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link DatePicker})
 * @param <B> 建構器本身的型態(需繼承{@link DatePickerMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface DatePickerMakerExt<Z extends DatePicker, B extends DatePickerMaker<Z, B>>
        extends javafx.scene.control.ComboBoxBaseMakerExt<java.time.LocalDate, Z, B>
{
    // nothing yet
}
