// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.control;

/**
 * {@link TableColumn}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class TableColumnBuilder<S extends java.lang.Object, T extends java.lang.Object, Z extends TableColumn<S, T>, B extends TableColumnBuilder<S, T, Z, B>>
        extends javafx.scene.control.TableColumnBaseBuilder<S, T, Z, B>
{

    protected boolean hasCellFactory;
    protected javafx.util.Callback<javafx.scene.control.TableColumn<S, T>, javafx.scene.control.TableCell<S, T>> valCellFactory;

    protected boolean hasCellValueFactory;
    protected javafx.util.Callback<javafx.scene.control.TableColumn.CellDataFeatures<S, T>, javafx.beans.value.ObservableValue<T>> valCellValueFactory;

    protected boolean hasColumns;
    protected java.util.Collection<javafx.scene.control.TableColumn<S, ?>> valColumns;

    protected boolean hasOnEditCancel;
    protected javafx.event.EventHandler<javafx.scene.control.TableColumn.CellEditEvent<S, T>> valOnEditCancel;

    protected boolean hasOnEditCommit;
    protected javafx.event.EventHandler<javafx.scene.control.TableColumn.CellEditEvent<S, T>> valOnEditCommit;

    protected boolean hasOnEditStart;
    protected javafx.event.EventHandler<javafx.scene.control.TableColumn.CellEditEvent<S, T>> valOnEditStart;

    protected boolean hasSortType;
    protected javafx.scene.control.TableColumn.SortType valSortType;

    protected boolean boundCellFactory;
    protected javafx.beans.value.ObservableValue<? extends javafx.util.Callback<javafx.scene.control.TableColumn<S, T>, javafx.scene.control.TableCell<S, T>>> obsrvCellFactory;

    protected boolean boundCellValueFactory;
    protected javafx.beans.value.ObservableValue<? extends javafx.util.Callback<javafx.scene.control.TableColumn.CellDataFeatures<S, T>, javafx.beans.value.ObservableValue<T>>> obsrvCellValueFactory;

    protected boolean boundOnEditCancel;
    protected javafx.beans.value.ObservableValue<? extends javafx.event.EventHandler<javafx.scene.control.TableColumn.CellEditEvent<S, T>>> obsrvOnEditCancel;

    protected boolean boundOnEditCommit;
    protected javafx.beans.value.ObservableValue<? extends javafx.event.EventHandler<javafx.scene.control.TableColumn.CellEditEvent<S, T>>> obsrvOnEditCommit;

    protected boolean boundOnEditStart;
    protected javafx.beans.value.ObservableValue<? extends javafx.event.EventHandler<javafx.scene.control.TableColumn.CellEditEvent<S, T>>> obsrvOnEditStart;

    protected boolean boundSortType;
    protected javafx.beans.value.ObservableValue<? extends javafx.scene.control.TableColumn.SortType> obsrvSortType;

    @Override
    public void applyTo(Z instance)
    {
        super.applyTo(instance);
        if (this.hasCellFactory)
            instance.setCellFactory(this.valCellFactory);
        if (this.hasCellValueFactory)
            instance.setCellValueFactory(this.valCellValueFactory);
        if (this.hasColumns)
            instance.getColumns().setAll(this.valColumns);
        if (this.hasOnEditCancel)
            instance.setOnEditCancel(this.valOnEditCancel);
        if (this.hasOnEditCommit)
            instance.setOnEditCommit(this.valOnEditCommit);
        if (this.hasOnEditStart)
            instance.setOnEditStart(this.valOnEditStart);
        if (this.hasSortType)
            instance.setSortType(this.valSortType);
        if (this.boundCellFactory)
            instance.cellFactoryProperty().bind(this.obsrvCellFactory);
        if (this.boundCellValueFactory)
            instance.cellValueFactoryProperty().bind(this.obsrvCellValueFactory);
        if (this.boundOnEditCancel)
            instance.onEditCancelProperty().bind(this.obsrvOnEditCancel);
        if (this.boundOnEditCommit)
            instance.onEditCommitProperty().bind(this.obsrvOnEditCommit);
        if (this.boundOnEditStart)
            instance.onEditStartProperty().bind(this.obsrvOnEditStart);
        if (this.boundSortType)
            instance.sortTypeProperty().bind(this.obsrvSortType);
    }

    /**
     * 設定屬性{@link TableColumn#setCellFactory}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B cellFactory(javafx.util.Callback<javafx.scene.control.TableColumn<S, T>, javafx.scene.control.TableCell<S, T>> value)
    {
        this.hasCellFactory = true;
        this.valCellFactory = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link TableColumn#setCellValueFactory}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B cellValueFactory(javafx.util.Callback<javafx.scene.control.TableColumn.CellDataFeatures<S, T>, javafx.beans.value.ObservableValue<T>> value)
    {
        this.hasCellValueFactory = true;
        this.valCellValueFactory = value;
        return (B) this;
    }

    /**
     * 設定集合屬性{@link TableColumn#getColumns}的內容
     *
     * @param value 新的集合內容
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B columns(java.util.Collection<javafx.scene.control.TableColumn<S, ?>> value)
    {
        this.hasColumns = true;
        this.valColumns = value;
        return (B) this;
    }

    /**
     * 設定集合屬性{@link TableColumn#getColumns}的內容
     *
     * @param value 新的集合內容
     * @return 目前的建構器(this)
     */
    @SafeVarargs
    @SuppressWarnings("unchecked")
    public final B columns(javafx.scene.control.TableColumn<S, ?>... value)
    {
        this.hasColumns = true;
        this.valColumns = java.util.Arrays.asList(value);
        return (B) this;
    }

    /**
     * 設定屬性{@link TableColumn#setOnEditCancel}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B onEditCancel(javafx.event.EventHandler<javafx.scene.control.TableColumn.CellEditEvent<S, T>> value)
    {
        this.hasOnEditCancel = true;
        this.valOnEditCancel = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link TableColumn#setOnEditCommit}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B onEditCommit(javafx.event.EventHandler<javafx.scene.control.TableColumn.CellEditEvent<S, T>> value)
    {
        this.hasOnEditCommit = true;
        this.valOnEditCommit = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link TableColumn#setOnEditStart}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B onEditStart(javafx.event.EventHandler<javafx.scene.control.TableColumn.CellEditEvent<S, T>> value)
    {
        this.hasOnEditStart = true;
        this.valOnEditStart = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link TableColumn#setSortType}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B sortType(javafx.scene.control.TableColumn.SortType value)
    {
        this.hasSortType = true;
        this.valSortType = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link TableColumn#cellFactoryProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B bindCellFactory(javafx.beans.value.ObservableValue<? extends javafx.util.Callback<javafx.scene.control.TableColumn<S, T>, javafx.scene.control.TableCell<S, T>>> source)
    {
        assert (source != null);
        this.boundCellFactory = true;
        this.obsrvCellFactory = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link TableColumn#cellValueFactoryProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B bindCellValueFactory(javafx.beans.value.ObservableValue<? extends javafx.util.Callback<javafx.scene.control.TableColumn.CellDataFeatures<S, T>, javafx.beans.value.ObservableValue<T>>> source)
    {
        assert (source != null);
        this.boundCellValueFactory = true;
        this.obsrvCellValueFactory = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link TableColumn#onEditCancelProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B bindOnEditCancel(javafx.beans.value.ObservableValue<? extends javafx.event.EventHandler<javafx.scene.control.TableColumn.CellEditEvent<S, T>>> source)
    {
        assert (source != null);
        this.boundOnEditCancel = true;
        this.obsrvOnEditCancel = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link TableColumn#onEditCommitProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B bindOnEditCommit(javafx.beans.value.ObservableValue<? extends javafx.event.EventHandler<javafx.scene.control.TableColumn.CellEditEvent<S, T>>> source)
    {
        assert (source != null);
        this.boundOnEditCommit = true;
        this.obsrvOnEditCommit = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link TableColumn#onEditStartProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B bindOnEditStart(javafx.beans.value.ObservableValue<? extends javafx.event.EventHandler<javafx.scene.control.TableColumn.CellEditEvent<S, T>>> source)
    {
        assert (source != null);
        this.boundOnEditStart = true;
        this.obsrvOnEditStart = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link TableColumn#sortTypeProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B bindSortType(javafx.beans.value.ObservableValue<? extends javafx.scene.control.TableColumn.SortType> source)
    {
        assert (source != null);
        this.boundSortType = true;
        this.obsrvSortType = source;
        return (B) this;
    }

    /**
     * 建構{@link TableColumn}物件
     *
     * @return 新的{@link TableColumn}物件實體
     */
    @Override
    @SuppressWarnings("unchecked")
    public TableColumn<S, T> build()
    {
        TableColumn<S, T> instance = new TableColumn<S, T>();
        this.applyTo((Z) instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
