// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.control;

/**
 * {@link ToggleButton}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link ToggleButton})
 * @param <B> 建構器本身的型態(需繼承{@link ToggleButtonBuilder})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class ToggleButtonBuilder<Z extends ToggleButton, B extends ToggleButtonBuilder<Z, B>>
        extends javafx.scene.control.ButtonBaseBuilder<Z, B>
{

    private boolean hasSelected;
    private boolean valSelected;

    private boolean hasToggleGroup;
    private javafx.scene.control.ToggleGroup valToggleGroup;

    private boolean boundSelected;
    private javafx.beans.value.ObservableValue<? extends Boolean> obsrvSelected;

    private boolean boundToggleGroup;
    private javafx.beans.value.ObservableValue<? extends javafx.scene.control.ToggleGroup> obsrvToggleGroup;

    @Override
    public void applyTo(Z instance)
    {
        super.applyTo(instance);
        if (this.hasSelected)
            instance.setSelected(this.valSelected);
        if (this.hasToggleGroup)
            instance.setToggleGroup(this.valToggleGroup);
        if (this.boundSelected)
            instance.selectedProperty().bind(this.obsrvSelected);
        if (this.boundToggleGroup)
            instance.toggleGroupProperty().bind(this.obsrvToggleGroup);
    }

    /**
     * 設定屬性{@link ToggleButton#setSelected(boolean)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B selected(boolean value)
    {
        this.hasSelected = true;
        this.valSelected = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link ToggleButton#setToggleGroup(javafx.scene.control.ToggleGroup)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B toggleGroup(javafx.scene.control.ToggleGroup value)
    {
        this.hasToggleGroup = true;
        this.valToggleGroup = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link ToggleButton#selectedProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindSelected(javafx.beans.value.ObservableValue<? extends Boolean> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundSelected = true;
        this.obsrvSelected = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link ToggleButton#toggleGroupProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindToggleGroup(javafx.beans.value.ObservableValue<? extends javafx.scene.control.ToggleGroup> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundToggleGroup = true;
        this.obsrvToggleGroup = source;
        return (B) this;
    }

    /**
     * 建構{@link ToggleButton}物件
     *
     * @return 新的{@link ToggleButton}物件實體
     */
    @Override
    @SuppressWarnings("unchecked")
    public ToggleButton build()
    {
        ToggleButton instance = new ToggleButton();
        this.applyTo((Z) instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
