// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.control.table;

/**
 * {@link TableMenuButtonAccessor}建構器延伸（供客製化）
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.0.6_20.jar
 * @param <Z> 要建構的物件型態(需繼承{@link TableMenuButtonAccessor})
 * @param <B> 建構器本身的型態(需繼承{@link TableMenuButtonAccessorBuilder})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface TableMenuButtonAccessorBuilderExt<Z extends TableMenuButtonAccessor, B extends TableMenuButtonAccessorBuilder<Z, B>>
        extends jxtn.jfx.builders.AbstractBuilderExt<Z, B>
{
    // nothing yet
}
