// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.control;

/**
 * {@link WorldMapView}建構器延伸（供客製化）。
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.40.14.jar
 * @param <Z> 要建構的物件型態(需繼承{@link WorldMapView})
 * @param <B> 建構器本身的型態(需繼承{@link WorldMapViewMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface WorldMapViewMakerExt<Z extends WorldMapView, B extends WorldMapViewMaker<Z, B>>
        extends javafx.scene.control.ControlMakerExt<Z, B>
{
    // nothing yet
}
