// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.control.cell;

/**
 * {@link TextFieldTableCell}建構器延伸（供客製化）
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link TextFieldTableCell})
 * @param <B> 建構器本身的型態(需繼承{@link TextFieldTableCellMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface TextFieldTableCellMakerExt<S extends java.lang.Object, T extends java.lang.Object, Z extends TextFieldTableCell<S, T>, B extends TextFieldTableCellMaker<S, T, Z, B>>
        extends javafx.scene.control.TableCellMakerExt<S, T, Z, B>
{
    // nothing yet
}
