// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.image;

/**
 * {@link WritablePixelFormat}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link WritablePixelFormat})
 * @param <B> 建構器本身的型態(需繼承{@link WritablePixelFormatBuilder})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class WritablePixelFormatBuilder<T extends java.nio.Buffer, Z extends WritablePixelFormat<T>, B extends WritablePixelFormatBuilder<T, Z, B>>
        extends javafx.scene.image.PixelFormatBuilder<T, Z, B>
{

    @Override
    public void applyTo(Z instance)
    {
        super.applyTo(instance);
    }
}
