// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.image;

/**
 * {@link WritableImage}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class WritableImageBuilder<Z extends WritableImage, B extends WritableImageBuilder<Z, B>>
        extends javafx.scene.image.ImageBuilder<Z, B>
{
    private boolean applied;
    public void applyTo(WritableImage instance)
    {
        super.applyTo(instance);
        if (this.applied)
            throw new IllegalStateException();
        //
        this.applied = true;
    }

    @SuppressWarnings("unchecked")
    public WritableImage build(int arg0, int arg1)
    {
        WritableImage instance = new WritableImage(arg0, arg1);
        this.applyTo(instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
