// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.tools;

/**
 * {@link ValueExtractor}建構器。
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.40.14.jar
 * @param <Z> 要建構的物件型態(需繼承{@link ValueExtractor})
 * @param <B> 建構器本身的型態(需繼承{@link ValueExtractorMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class ValueExtractorMaker<Z extends ValueExtractor, B extends ValueExtractorMaker<Z, B>>
        extends jxtn.jfx.makers.AbstractMaker<Z, B>
        implements ValueExtractorMakerExt<Z, B>
{

    @Override
    public void applyTo(Z instance)
    {
        super.applyTo(instance);
    }
}
