// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.image;

/**
 * {@link Image}建構器延伸（供客製化）
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link Image})
 * @param <B> 建構器本身的型態(需繼承{@link ImageMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface ImageMakerExt<Z extends Image, B extends ImageMaker<Z, B>>
        extends jxtn.jfx.makers.AbstractMakerExt<Z, B>
{
    // nothing yet
}
