// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.control.action;

/**
 * {@link ActionGroup}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.0.6_20.jar
 * @param <Z> 要建構的物件型態(需繼承{@link ActionGroup})
 * @param <B> 建構器本身的型態(需繼承{@link ActionGroupBuilder})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class ActionGroupBuilder<Z extends ActionGroup, B extends ActionGroupBuilder<Z, B>>
        extends org.controlsfx.control.action.AbstractActionBuilder<Z, B>
        implements ActionGroupBuilderExt<Z, B>
{

    private boolean hasActions;
    private java.util.Collection<org.controlsfx.control.action.Action> valActions;

    @Override
    public void applyTo(Z instance)
    {
        super.applyTo(instance);
        if (this.hasActions)
            instance.getActions().addAll(this.valActions);
    }

    /**
     * 設定集合屬性{@link ActionGroup#getActions}的內容
     *
     * @param value 新的集合內容
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B actions(java.util.Collection<org.controlsfx.control.action.Action> value)
    {
        this.hasActions = true;
        this.valActions = value;
        return (B) this;
    }

    /**
     * 設定集合屬性{@link ActionGroup#getActions}的內容
     *
     * @param value 新的集合內容
     * @return 目前的建構器(this)
     */
    @SafeVarargs
    @SuppressWarnings("unchecked")
    public final B actions(org.controlsfx.control.action.Action... value)
    {
        this.hasActions = true;
        this.valActions = java.util.Arrays.asList(value);
        return (B) this;
    }

    /**
     * 增加集合屬性{@link ActionGroup#getActions}的內容
     *
     * @param value 新的集合內容
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B actionsAdd(java.util.Collection<org.controlsfx.control.action.Action> value)
    {
        java.util.Objects.requireNonNull(value);
        this.hasActions = true;
        if (this.valActions == null)
            this.valActions = new java.util.ArrayList<>(value.size());
        this.valActions.addAll(value);
        return (B) this;
    }

    /**
     * 增加集合屬性{@link ActionGroup#getActions}的內容
     *
     * @param value 新的集合內容
     * @return 目前的建構器(this)
     */
    @SafeVarargs
    @SuppressWarnings("unchecked")
    public final B actionsAdd(org.controlsfx.control.action.Action... value)
    {
        java.util.Objects.requireNonNull(value);
        this.hasActions = true;
        if (this.valActions == null)
            this.valActions = new java.util.ArrayList<>(value.length);
        this.valActions.addAll(java.util.Arrays.asList(value));
        return (B) this;
    }

    /**
     * 建構{@link ActionGroup}物件
     *
     * @return 新的{@link ActionGroup}物件實體
     */
    @SuppressWarnings("unchecked")
    public ActionGroup build(java.lang.String arg0, java.util.Collection<org.controlsfx.control.action.Action> arg1)
    {
        ActionGroup instance = new ActionGroup(arg0, arg1);
        this.applyTo((Z) instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
