// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.transform;

/**
 * {@link NonInvertibleTransformException}建構器延伸（供客製化）
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link NonInvertibleTransformException})
 * @param <B> 建構器本身的型態(需繼承{@link NonInvertibleTransformExceptionBuilder})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface NonInvertibleTransformExceptionBuilderExt<Z extends NonInvertibleTransformException, B extends NonInvertibleTransformExceptionBuilder<Z, B>>
        extends jxtn.jfx.builders.AbstractBuilderExt<Z, B>
{
    // nothing yet
}
