// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.transform;

/**
 * {@link NonInvertibleTransformException}建構器。
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link NonInvertibleTransformException})
 * @param <B> 建構器本身的型態(需繼承{@link NonInvertibleTransformExceptionMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class NonInvertibleTransformExceptionMaker<Z extends NonInvertibleTransformException, B extends NonInvertibleTransformExceptionMaker<Z, B>>
        extends jxtn.jfx.makers.AbstractMaker<Z, B>
        implements NonInvertibleTransformExceptionMakerExt<Z, B>
{

    @Override
    public void applyTo(Z instance)
    {
        super.applyTo(instance);
    }

    /**
     * 建構{@link NonInvertibleTransformException}物件。
     *
     * @return 新的{@link NonInvertibleTransformException}物件實體
     */
    @SuppressWarnings("unchecked")
    public NonInvertibleTransformException build(java.lang.String arg0)
    {
        NonInvertibleTransformException instance = new NonInvertibleTransformException(arg0);
        this.applyTo((Z) instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
