// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.transform;

/**
 * {@link Translate}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 * @param <Z> 要建構的物件型態(需繼承{@link Translate})
 * @param <B> 建構器本身的型態(需繼承{@link TranslateBuilder})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class TranslateBuilder<Z extends Translate, B extends TranslateBuilder<Z, B>>
        extends javafx.scene.transform.TransformBuilder<Z, B>
{

    private boolean hasX;
    private double valX;

    private boolean hasY;
    private double valY;

    private boolean hasZ;
    private double valZ;

    private boolean boundX;
    private javafx.beans.value.ObservableValue<? extends Double> obsrvX;

    private boolean boundY;
    private javafx.beans.value.ObservableValue<? extends Double> obsrvY;

    private boolean boundZ;
    private javafx.beans.value.ObservableValue<? extends Double> obsrvZ;

    @Override
    public void applyTo(Z instance)
    {
        super.applyTo(instance);
        if (this.hasX)
            instance.setX(this.valX);
        if (this.hasY)
            instance.setY(this.valY);
        if (this.hasZ)
            instance.setZ(this.valZ);
        if (this.boundX)
            instance.xProperty().bind(this.obsrvX);
        if (this.boundY)
            instance.yProperty().bind(this.obsrvY);
        if (this.boundZ)
            instance.zProperty().bind(this.obsrvZ);
    }

    /**
     * 設定屬性{@link Translate#setX(double)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B x(double value)
    {
        this.hasX = true;
        this.valX = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link Translate#setY(double)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B y(double value)
    {
        this.hasY = true;
        this.valY = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link Translate#setZ(double)}
     *
     * @param value 新的屬性值
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public B z(double value)
    {
        this.hasZ = true;
        this.valZ = value;
        return (B) this;
    }

    /**
     * 設定屬性{@link Translate#xProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindX(javafx.beans.value.ObservableValue<? extends Double> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundX = true;
        this.obsrvX = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link Translate#yProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindY(javafx.beans.value.ObservableValue<? extends Double> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundY = true;
        this.obsrvY = source;
        return (B) this;
    }

    /**
     * 設定屬性{@link Translate#zProperty}的連結
     *
     * @param value 新的屬性連結(單向)
     * @return 目前的建構器(this)
     */
    @SuppressWarnings("unchecked")
    public final B bindZ(javafx.beans.value.ObservableValue<? extends Double> source)
    {
        java.util.Objects.requireNonNull(source);
        this.boundZ = true;
        this.obsrvZ = source;
        return (B) this;
    }

    /**
     * 建構{@link Translate}物件
     *
     * @return 新的{@link Translate}物件實體
     */
    @Override
    @SuppressWarnings("unchecked")
    public Translate build()
    {
        Translate instance = new Translate();
        this.applyTo((Z) instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
