// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.glyphfont;

/**
 * {@link GlyphFontRegistry}建構器。
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.20.7.jar
 * @param <Z> 要建構的物件型態(需繼承{@link GlyphFontRegistry})
 * @param <B> 建構器本身的型態(需繼承{@link GlyphFontRegistryBuilder})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class GlyphFontRegistryBuilder<Z extends GlyphFontRegistry, B extends GlyphFontRegistryBuilder<Z, B>>
        extends jxtn.jfx.builders.AbstractBuilder<Z, B>
        implements GlyphFontRegistryBuilderExt<Z, B>
{

    @Override
    public void applyTo(Z instance)
    {
        super.applyTo(instance);
    }
}
