// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.glyphfont;

/**
 * {@link Glyph}建構器延伸（供客製化）
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.40.10.jar
 * @param <Z> 要建構的物件型態(需繼承{@link Glyph})
 * @param <B> 建構器本身的型態(需繼承{@link GlyphMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface GlyphMakerExt<Z extends Glyph, B extends GlyphMaker<Z, B>>
        extends javafx.scene.control.LabelMakerExt<Z, B>
{
    // nothing yet
}
