// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.control.spreadsheet;

/**
 * {@link SpreadsheetCellType.ObjectType}建構器延伸（供客製化）。
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.20.8.jar
 * @param <Z> 要建構的物件型態(需繼承{@link SpreadsheetCellType.ObjectType})
 * @param <B> 建構器本身的型態(需繼承{@link SpreadsheetCellType_ObjectTypeMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public interface SpreadsheetCellType_ObjectTypeMakerExt<Z extends SpreadsheetCellType.ObjectType, B extends SpreadsheetCellType_ObjectTypeMaker<Z, B>>
        extends org.controlsfx.control.spreadsheet.SpreadsheetCellTypeMakerExt<java.lang.Object, Z, B>
{
    // nothing yet
}
