// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package javafx.scene.effect;

/**
 * {@link Glow}建構器
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version jfxrt.jar
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class GlowBuilder<Z extends Glow, B extends GlowBuilder<Z, B>>
        extends javafx.scene.effect.EffectBuilder<Z, B>
{
    private boolean applied;

    protected boolean hasInput;
    protected javafx.scene.effect.Effect valInput;

    protected boolean hasLevel;
    protected double valLevel;

    protected boolean boundInput;
    protected javafx.beans.value.ObservableValue<? extends javafx.scene.effect.Effect> obsrvInput;

    protected boolean boundLevel;
    protected javafx.beans.value.ObservableValue<? extends Double> obsrvLevel;
    public void applyTo(Glow instance)
    {
        super.applyTo(instance);
        if (this.applied)
            throw new IllegalStateException();
        if (this.hasInput)
            instance.setInput(this.valInput);
        if (this.hasLevel)
            instance.setLevel(this.valLevel);
        if (this.boundInput)
            instance.inputProperty().bind(this.obsrvInput);
        if (this.boundLevel)
            instance.levelProperty().bind(this.obsrvLevel);
        //
        this.applied = true;
    }

    @SuppressWarnings("unchecked")
    public B input(javafx.scene.effect.Effect value)
    {
        this.hasInput = true;
        this.valInput = value;
        return (B) this;
    }

    @SuppressWarnings("unchecked")
    public B level(double value)
    {
        this.hasLevel = true;
        this.valLevel = value;
        return (B) this;
    }

    @SuppressWarnings("unchecked")
    public B bindInput(javafx.beans.value.ObservableValue<? extends javafx.scene.effect.Effect> source)
    {
        assert (source != null);
        this.boundInput = true;
        this.obsrvInput = source;
        return (B) this;
    }

    @SuppressWarnings("unchecked")
    public B bindLevel(javafx.beans.value.ObservableValue<? extends Double> source)
    {
        assert (source != null);
        this.boundLevel = true;
        this.obsrvLevel = source;
        return (B) this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Glow build()
    {
        Glow instance = new Glow();
        this.applyTo(instance);
        this.doAfterBuild((Z) instance);
        return instance;
    }
}
