// @formatter:off
/*
 * Unlicensed, generated by javafx.ftl
 */

package org.controlsfx.control.spreadsheet;

/**
 * {@link StringConverterWithFormat}建構器。
 *
 * @author JarReflectionDataLoader-1.0.0
 * @version controlsfx-8.40.14.jar
 * @param <Z> 要建構的物件型態(需繼承{@link StringConverterWithFormat})
 * @param <B> 建構器本身的型態(需繼承{@link StringConverterWithFormatMaker})
 */
@javax.annotation.Generated("Generated by javafx.ftl")
@SuppressWarnings("all")
public class StringConverterWithFormatMaker<T extends java.lang.Object, Z extends StringConverterWithFormat<T>, B extends StringConverterWithFormatMaker<T, Z, B>>
        extends jxtn.jfx.makers.AbstractMaker<Z, B>
        implements StringConverterWithFormatMakerExt<T, Z, B>
{

    @Override
    public void applyTo(Z instance)
    {
        super.applyTo(instance);
    }
}
